import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FranNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bongocat.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Frannyext!</a>
        </h1>

        <p className={styles.description}>
          Get started by taking care of a cat!
        </p>
      </main>
    </div>
  );
}
