import Head from "next/head";

import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RePokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bongocat.png" />
      </Head>

      <main className={styles.main}>
        <ul className={styles.menu}>
          <li>
            <Link href="/">
              <a>Home</a>
            </Link>
          </li>
          <li>
            <Link href="/pokemon">
              <a>Pokemon</a>
            </Link>
          </li>
          <li>
            <Link href="/pokedexSSR">
              <a>My Pokedex SSR</a>
            </Link>
          </li>
          <li>
            <Link href="/pokedexSSG">
              <a>My Pokedex SSG</a>
            </Link>
          </li>
          <li>
            <Link href="/pokedexISR">
              <a>My Pokedex ISR</a>
            </Link>
          </li>
        </ul>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Frannyext!</a>
        </h1>

        <p className={styles.description}>
          Get started by taking care of a cat!
        </p>
      </main>
    </div>
  );
}
